version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local
  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    networks:
      - local
  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local: